FROM mambaorg/micromamba:1.5.10-noble AS build

COPY --chown=$MAMBA_USER:$MAMBA_USER conda.yml /tmp/conda.yml

RUN (micromamba install -y -n base -f /tmp/conda.yml > /tmp/mamba.log 2>&1 \
    && cat /tmp/mamba.log \
    || (cat /tmp/mamba.log >&2 && grep -q __cuda /tmp/mamba.log \
        && CONDA_OVERRIDE_CUDA="99" micromamba install -y -n base -f /tmp/conda.yml)) \
    && micromamba install -y -n base conda-forge::procps-ng \
    && micromamba clean -a -y \
    && micromamba env export --name base --explicit > environment.lock \
    && echo ">> CONDA_LOCK_START" \
    && cat environment.lock \
    && echo "<< CONDA_LOCK_END"

FROM ubuntu:24.04 AS prod

ARG MAMBA_ROOT_PREFIX="/opt/conda"
ENV MAMBA_ROOT_PREFIX=$MAMBA_ROOT_PREFIX

COPY --from=build "$MAMBA_ROOT_PREFIX" "$MAMBA_ROOT_PREFIX"

USER root

# Install git so we can clone the repository
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="$MAMBA_ROOT_PREFIX/bin:$PATH"

# Clone KEMET
WORKDIR /opt
RUN git clone https://github.com/Matteopaluh/KEMET.git

# Set working directory to the repository
WORKDIR /opt/KEMET